### ISSUE TITLE
what did i break?

### ISSUE THREAD

**Issue by mrmazakblu** [twrpdtgen/twrpdtgen#106]
I know i had this issue before. What do i need to do to get past this error?

mrmazak@mrmazak-ThinkCentre-M91p:~/dumpyara/dumpyara$ python3 -m twrpdtgen -h
TWRP device tree generator
Python Edition
Version 1.0.0

Error: Please clone the script with Git instead of downloading it as a zip

I have cloned the git and installed python3(maybe i messed this install up??)

here is a clip from running in  dumpyara script....

"

- incremental: 1629963840
- tags: release-keys
- fingerprint: ATT/U318AA/U318AA:10/QP1A.190711.020/1629963840:user/release-keys
- is_ab: false
- brand: ATT
- branch: full_u318-user-10-QP1A.190711.020-1629963840-release-keys
- repo: att_u318aa_dump
TWRP device tree generator
Python Edition
Version 1.0.0

Error: Please clone the script with Git instead of downloading it as a zip
dumpyara.sh: line 182: /home/mrmazak/dumpyara/dumpyara/working/calipso/twrp-device-tree/README.md: No such file or directory
all_files.txt
board-info.txt

|"

I get same error when i run twrpdtgen directly too.\

**Comment by SebaUbuntu** [comment]
`pip install -u twrpdtgen`
If Python 3.9 is the problem, install it and do `python3.9 -m pip install twrpdtgen`
