### ISSUE TITLE
[Question] Can I use this tool to create a trwp image for an Android 11 device?

### ISSUE THREAD

**Issue by thomasplus** [twrpdtgen/twrpdtgen#123]
Hi,

The latest branch of `platform_manifest_twrp_omni` is `twrp-9.0`. I tried to extract the boot.img from the `Xiaomi Mi 12X` image (based on android 11) and successfully compiled an image according to the wiki. Can I flash it safely? 

Or do I have to use the branch `android-11` in [platform_manifest_twrp_aosp](https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp) to compile it? What's the difference between using `twrp-9.0` and using `android-11` branch?

Thanks.

**Comment by SebaUbuntu** [comment]
You need to use Android 11 one
