### ISSUE TITLE
No module named 'sebaubuntu_libs.libprop'

### ISSUE THREAD

**Issue by Tarch1** [twrpdtgen/twrpdtgen#128]
Sorry for bother you, after the very start, the script stopped for this error. I've installed twrpdtgen without any error from pip, don't know what is wrong...

**Comment by SebaUbuntu** [comment]
Fixed with https://github.com/twrpdtgen/twrpdtgen/commit/95f2692e5cc2682ad24ab79e7831f5fe38d6e0ce

I still need to release it to PyPI

**Comment by Tarch1** [comment]
Thanks for the fast reply ☺️

**Comment by Tarch1** [comment]
Hi, 
I've tried to manually edit those file you had changed 14th july, and the script work until 
raise RuntimeError(f"AIK extraction failed, return code {returncode}")
RuntimeError: AIK extraction failed, return code 1

**Comment by SebaUbuntu** [comment]
v2.3.1 release to PyPI
