### ISSUE TITLE
Twrp 11 device tree

### ISSUE THREAD

**Issue by Arafattex** [twrpdtgen/twrpdtgen#130]
It works well but you know that twrp is now update and in twrp 11 it is aosp not omni...

So when i creat device tree it creat tree for twrp 10 but it cannot made twrp 11 tree...

Would you fix it ??

**Comment by Poempoat** [comment]
it works for me:
ln -sr vendor/omni vendor/twrp

**Comment by Darkweber0009** [comment]
Problem! AIK extraction failed, return code 1  any solution please

**Comment by Arafattex** [comment]
Tnx i understand
