### ISSUE TITLE
twrpdtgen generates for omni instead of specifically twrp

### ISSUE THREAD

**Issue by smaybius** [twrpdtgen/twrpdtgen#136]
Is it really meant to build for specifically omnirom? Maybe it should be made for the minimal manifest (https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp) instead of a specific system like omni or lineage. Or, maybe it should be split into options based on arguments?

**Comment by SebaUbuntu** [comment]
If you need something newer that uses the twrp build system, then please use aospdtgen
