### ISSUE TITLE
Compiled successfully but no img images were generated with 3.0

### ISSUE THREAD

**Issue by h0we** [twrpdtgen/twrpdtgen#137]
Device : lenovo legion y70

Device tree : https://github.com/h0we/android_device_lenovo_halo_twrp

Stock recovery image : https://raw.githubusercontent.com/h0we/android_device_lenovo_halo_twrp/12.1/stock/recovery.img

Build recovery image : no img was generated

Build log : https://pastebin.ubuntu.com/p/X6vfHHn4Nx/

out volume : 
![image](https://user-images.githubusercontent.com/102644729/197931444-b2699abb-774e-4b10-8584-6ff6634672b7.png)

**Comment by SebaUbuntu** [comment]
I'm guessing you used the wrong commands
