### ISSUE TITLE
Does this work for samsung devices?

### ISSUE THREAD

**Issue by TheSpartaPT** [twrpdtgen/twrpdtgen#139]
Hi, i've extracted recovery.img from my phone's (Samsung a7y18lte) latest firmware (AP .tar) but it doesn't seem to be working.

am I doing something wrong ? does it not support samsung firmware files ?

this is the command I ran:
`python -m twrpdtgen -d recovery.img`

![image](https://user-images.githubusercontent.com/8343238/198847803-3ac785e0-2a98-4ceb-849a-c400df620b01.png)

here's the firmware too: https://samfw.com/firmware/SM-A750FN/TPH/A750FNXXU5CVG2

**Comment by SebaUbuntu** [comment]
Please check if AIK is able to extract that image
