### ISSUE TITLE
device tree is "faulty"

### ISSUE THREAD

**Issue by scopiwolf** [twrpdtgen/twrpdtgen#153]
Hello, I have successfully used this tool, and it made the dt successfully, but when I try to build twrp I get this error:

[ 99% 689/690] glob frameworks/base/core/res/res/**/*
ninja: error: '/home/pmagix/ofrp/sync/out/target/product/fiji_64/obj/STATIC_LIBRARIES/bootctrl.mt6765_intermediates/export_includes', needed by '/home/pmagix/ofrp/sync/out/target/product/fiji_64/obj/EXECUTABLES/update_engine_sideload_intermediates/import_includes', missing and no known rule to make it

Could someone help?

**Comment by SebaUbuntu** [comment]
A/B support kind of wacky, it requires manual intervention anyway
