### ISSUE TITLE
Build sandboxing disabled due to nsjail error

### ISSUE THREAD

**Issue by Lyinceer** [twrpdtgen/twrpdtgen#208]
17:15:49 Build sandboxing disabled due to nsjail error.
In file included from build/make/core/config.mk:291:
In file included from build/make/core/envsetup.mk:266:
build/make/core/product_config.mk:155: error: Can not locate config makefile for product "omni_a55x".
17:15:49 dumpvars failed with: exit status 1
Device a55x not found. Attempting to retrieve device repository from TeamWin Github (http://github.com/TeamWin).
Repository for a55x not found in the TeamWin Github repository list.
If this is in error, you may need to manually add it to your .repo/local_manifests/roomservice.xml
17:15:52 Build sandboxing disabled due to nsjail error.
In file included from build/make/core/config.mk:291:
In file included from build/make/core/envsetup.mk:266:
build/make/core/product_config.mk:155: error: Can not locate config makefile for product "omni_a55x".
17:15:52 dumpvars failed with: exit status 1
17:15:54 Build sandboxing disabled due to nsjail error.
In file included from build/make/core/config.mk:291:
In file included from build/make/core/envsetup.mk:266:
build/make/core/product_config.mk:155: error: Can not locate config makefile for product "omni_a55x".
17:15:54 dumpvars failed with: exit status 1

** Don't have a product spec for: 'omni_a55x'

I actually skip the steps to build the twrp device tree manually as of before i've generated the device tree with tree generator 
built-in bot (since i don't know my device is using recovery but the recovery image is not in the stock rom, there are only, i fully uploaded the stock rom into the generator and got the device tree as output = [Device tree](https://github.com/twrpdtgen/android_device_samsung_essi)

**Comment by SebaUbuntu** [comment]
Follow the wiki properly, take a look at where to place the device tree
