### ISSUE TITLE
Unable to build vendorbootimage

### ISSUE THREAD

**Issue by CaptialState** [twrpdtgen/twrpdtgen#211]
Expected the `vendorbootimage` to show up in out/ but none found, Although the build completed successfully.

https://github.com/CaptialState/android_device_xiaomi_air (Device Tree)
https://pastebin.com/XRv12hhQ (Build Log)

**Comment by SebaUbuntu** [comment]
Use [aospdtgen](https://github.com/sebaubuntu-python/aospdtgen) with LineageOS instead.
