### ISSUE TITLE
[Request] Ask for Device Name

### ISSUE THREAD

**Issue by jasonmerc** [twrpdtgen/twrpdtgen#213]
I ran the twrpdtgen script, and the only error it had was the following:

_AssertionError: Property ro.product.system.device could not be found in build.prop_

I was able to manually unpack my stock recovery image, add that as a line to the default.prop, and repack it.  The script then ran without a problem.  By default the value was stored under "ro.build.product".  I guess some phones don't use product.system.device anymore.

So my request is, for something simple like a missing device name, can the script be modified so that it can prompt the user to input a device name value manually instead of erroring out entirely?

**Comment by SebaUbuntu** [comment]
No
